### Criar account
POST http://localhost:3000/account
Content-Type: application/json

{
    "name": "Calopsita",
    "balance": 20009999900
}

### GET de todas accounts
GET http://localhost:3000/account

### GET de uma account por id
GET http://localhost:3000/account/3

### DELETE de uma account por id
DELETE http://localhost:3000/account/2

### Atualização PUT de uma account por id
PUT http://localhost:3000/account
Content-Type: application/json

{
      "id": 3,
      "name": "Carlos André",
      "balance": 3
}

### Atualização PATCH de balance da account por id
PATCH http://localhost:3000/account/updateBalance
Content-Type: application/json

{
      "id": 3,
      "balance": 22222
}